### ISSUE TITLE
Correct grammar on Digest subject lines

### ISSUE THREAD

**Issue by jamjensen** [DoSomething/mbc-digest-email#81] opened 2016-06-30 15:35 UTC
_BUG_
-------------------
#### Current Behavior
One of the Campaign Digest subject lines reads, "Its your weekly..." instead of, **"It's** your..."

#### Desired Behavior
Subject line should have read It's instead of Its. 

#### Relevant Screenshots + Links

![image](https://cloud.githubusercontent.com/assets/19572934/16494280/b69be630-3eb6-11e6-9c9a-c1c7e5973f88.png)

@DeeZone 

**Existing Values**:
https://github.com/DoSomething/mbc-digest-email/blob/master/src/MBC_DigestEmail_MandrillMessenger.php#L361-L387

**Comment by DeeZone** [comment] 2016-07-01 00:55
Ah this is because there's a long standing bug in Mandrill. The "'" is not supported in subject lines!!

**Comment by jamjensen** [comment] 2016-07-07 14:56
@DeeZone f/u on this -- Do you know where can we rewrite the subject lines? Is it in the code or in Mandrill?

**Comment by DeeZone** [comment] 2016-07-12 19:08
Checked in with Mandrill Support on this issue and confirmed by trying to generate a test message with a template via the Mandrill UI. The apostrophe character "'" is not supported in the message subject line.

Please close this issue if you feel your question has been answered.

**Comment by DeeZone** [comment] 2016-07-13 18:52
@jamjensen 

Word from Mandrill Support say apostrophe use in message subject lines via the API are now supported (details below). I'll create the code change with your requested edit:
> "Its your weekly..." instead of, "It's your..."

Are there any other additions, deletions, changes you would like to make?

```
David (Mandrill Support)
Jul 13, 12:42 PM EDT

Hi Darren,

Thanks for getting in touch. Apostrophes on the default subject lines of templates are not supported, however, using apostrophes on the subject line of any API call or SMTP request will work fine without any issue.

Please let us know if you have any additional questions.

Darren Lee
Jul 12, 3:05 PM EDT

In the past we reported a bug where apostrophes in the subject line were not supported due to a known bug that resulted in the apostrophe character being precluded with an escape "\" character.

Is this still an issue or is using "'" in message subject lines supported?
```

**Closed** 2016-07-13 19:39 UTC
